### ISSUE TITLE
Get dogBreed data from database

### ISSUE THREAD

**Issue by haakonjacobsen** [haakonjacobsen/bark#64]
TODOs:

- [x] Scrape data and put data in MongoDB
- [x] Create scraper mongoose model and new endpoints
- [x] Display data in frontend

**Comment by AndreasWintherMoen** [comment]
Scrape data and put data in MongoDB resolved in #69

**Comment by AndreasWintherMoen** [comment]
Create scraper mongoose model and new endpoints solved in #72

**Comment by AndreasWintherMoen** [comment]
Display data in frontend solved in #80
