### ISSUE TITLE
Make DogTag index prettier

### ISSUE THREAD

**Issue by AndreasWintherMoen** [haakonjacobsen/bark#79]
See Figma.

**Comment by haakonjacobsen** [comment]
<img width="698" alt="Screenshot 2022-09-10 at 06 23 23" src="https://user-images.githubusercontent.com/15661593/189468599-715e897b-2bc4-405a-bbc0-8f42b9ac3afe.png">

**Comment by haakonjacobsen** [comment]
Something like this:
<img width="715" alt="Screenshot 2022-09-10 at 06 25 10" src="https://user-images.githubusercontent.com/15661593/189468631-cd8c8981-a5ae-4b5b-88ef-c2e0aa4c7e1d.png">
